config/routes.rb
Rails.application.routes.draw do
  get '/blogs', to: 'blogs#index'
  resources :blogs do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :name, :content, presence: true
    validates :content, length: { minimum: 140 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
      @blogs = Blog.all
   
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "You have deleted the blog!"
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.create(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "You have created new blog!"
    else
      render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "You have edited this blog！"
    else
      render :edit
    end
  end
  def redirecting
    redirect_to blogs_path, notice: "You have edited this blog！"
  end
  private
  def blog_params
    params.require(:blog).permit(:name, :content, :dob)
  end
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
          confirm_blogs_path
        elsif action_name == 'edit'
          blog_path
        end
      end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>

app/views/blogs/confirm.html.erb
<h3>Send it with the following contents.</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :dob %>

  <p>Title:<%= @blog.name %></p>
  <p>Body:<%= @blog.dob %></p>
  <%= form.submit  "submit" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :dob %>
  <%= form.submit "back" %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  

    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= @blog.errors.count %>errors occurred.</h2>
        <ul>
  
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
      <div class="blog_title">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="blog_title">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
      <div class="blog_title">
        <%= form.label :date %>
        <%= form.text_field :dob %>
      </div>
      <%= form.submit %>
      <%= link_to "Return to List of blogs screen", blogs_path %>
    <% end %>

app/views/blogs/index.html.erb
<h1>List of blogs</h1>

<p><%= notice %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Contents</th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
  <tr>
    <td><%= blog.name %></td>
    <td><%= blog.content %></td>
    <td><%= blog.date %></td>
    <td><%= link_to link_to 'Check the details', blog_path(blog.id) %></td>
    <td><%= link_to link_to "Edit this blog", edit_blog_path(blog.id) %></td>
    <!-- Define here! -->
    <td><%= link_to link_to 'Delete this blos', blog_path(blog.id), method: :delete %></td>
  </tr>
  </tr>
<% end %>

</table>

<br>

<%= link_to 'Post a new blog', new_blog_path %>

app/views/blogs/new.html.erb
<%= form_with(model: Blog.new, local: true) do |form| %>
  

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>errors occurred.</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="blog_title">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
    <div class="blog_title">
      <%= form.label :dob %>
      <%= form.text_field :dob %>
    </div>
    <%= form.submit %>
    <%= link_to "Return to List of blogs screen", blogs_path %>
  <% end %>

app/views/blogs/show.html.erb
<h1>Blog Detail Screen </h1>
<p>Title: <%= @blog.name %></p>
<p>Contents: <%= @blog.content %></p>
<p>date: <%= @blog.dob %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>